SELECT * FROM people, study, login, publicMessages, comments, privateMessages, category
WHERE people.id = login.personid AND (people.id = privateMessages.senderid OR people.id = privateMessages.recipientid) 
AND people.id = comments.senderid AND publicMessages.senderid = people.id AND people.studyid = study.id
AND comments.messageid = publicMessages.id AND publicMessages.categoryid = category.id;

INSERT INTO category(name)
VALUES ('Dansk'),
       ('Engelsk'),
       ('Tysk'),
       ('Andet sprog'),
       ('Matematik'),
       ('Fysik'),
       ('Kemi'),
       ('Biologi'),
       ('Historie'),
       ('Idehistorie'),
       ('Samfundsfag'),
       ('Religion'),
       ('Geografi'),
       ('Idræt'),
       ('Programmering'),
       ('Design'),
       ('Psykologi'),
       ('Filosofi'),
       ('Erhvervsøkonomi'),
       ('Innovation'),
       ('Teknologi'),
       ('Teknikfag'),
       ('Kommunikation og IT'),
       ('Informatik'),
       ('Økonomi'),
       ('Studieområdeprojekt (SOP)'),
       ('Studieretningsprojekt (SRP)'),
       ('Større skriftlig opgave (SSO)'),
       ('Studieretningsopgave (SRO)'),
       ('Studieretningscase (SRC)'),
       ('Obligatorisk selvvalgt opgave (OSO)'),
       ('Dansk-Idehistorie opgave (DIO)'),
       ('Det internationale område (DIO)'),
       ('Eksamen'),
       ('Tutor'),
       ('Andet');