INSERT INTO category(name)
VALUES ('Dansk'),
       ('Engelsk'),
       ('Tysk'),
       ('Andet sprog'),
       ('Matematik'),
       ('Fysik'),
       ('Kemi'),
       ('Biologi'),
       ('Historie'),
       ('Idehistorie'),
       ('Samfundsfag'),
       ('Religion'),
       ('Geografi'),
       ('Idræt'),
       ('Programmering'),
       ('Design'),
       ('Psykologi'),
       ('Filosofi'),
       ('Erhvervsøkonomi'),
       ('Innovation'),
       ('Teknologi'),
       ('Teknikfag'),
       ('Kommunikation og IT'),
       ('Informatik'),
       ('Økonomi'),
       ('Studieområdeprojekt (SOP)'),
       ('Studieretningsprojekt (SRP)'),
       ('Større skriftlig opgave (SSO)'),
       ('Studieretningsopgave (SRO)'),
       ('Studieretningscase (SRC)'),
       ('Obligatorisk selvvalgt opgave (OSO)'),
       ('Dansk-Idehistorie opgave (DIO)'),
       ('Det internationale område (DIO)'),
       ('Eksamen'),
       ('Tutor'),
       ('Andet');